version: '3'

networks:
  default-network:
    driver: bridge
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - default-network
    ports:
      - 3306:3306
  # rabbitmq:
  #   image: rabbitmq:3.7.8-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=rabbitmq
  #     - RABBITMQ_DEFAULT_PASS=rabbitmq
  #   healthcheck:
  #     test: [ "CMD", "rabbitmqctl", "status" ]
  #     interval: 20s
  #     timeout: 5s
  #     retries: 10
  #   networks:
  #     - default-network